/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AtomPalette {
        /**
          * The primary color hex value of the palette e.g. #912bff
         */
        "primary": string;
        "secondary": string;
    }
}
declare global {
    interface HTMLAtomPaletteElement extends Components.AtomPalette, HTMLStencilElement {
    }
    var HTMLAtomPaletteElement: {
        prototype: HTMLAtomPaletteElement;
        new (): HTMLAtomPaletteElement;
    };
    interface HTMLElementTagNameMap {
        "atom-palette": HTMLAtomPaletteElement;
    }
}
declare namespace LocalJSX {
    interface AtomPalette {
        /**
          * The primary color hex value of the palette e.g. #912bff
         */
        "primary"?: string;
        "secondary"?: string;
    }
    interface IntrinsicElements {
        "atom-palette": AtomPalette;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "atom-palette": LocalJSX.AtomPalette & JSXBase.HTMLAttributes<HTMLAtomPaletteElement>;
        }
    }
}
